# Nightfall: Secret Roles — local build helper (generated by the dreamcrafters CI kit)
#
#   make build        lint → typecheck → bundle (expo export)       ← lint is ON by default
#   make build-lint   same as build, lint forced on even if LINT=0 in local.mk
#   make build-test   lint → typecheck → unit tests → i18n → bundle
#   make check        lint + typecheck + tests + i18n, no bundle
#   make eas-build    queue a cloud EAS build   (PROFILE=preview|production, PLATFORM=android|ios|all)
#   make release      build-test, then EAS production build + submit to Play internal (draft)
#   make help         everything else
#
# Toggles: pass on the command line (make build TEST=1 LINT=0) or put them in local.mk
# (git-ignored), e.g. a line   TEST := 1
#
# Windows: install GNU make once (winget install ezwinports.make, or choco install make) and run
# from Git Bash, PowerShell or cmd — recipes only use npm/npx/node so they work in all three.

# Defaults use := so stray environment variables (Windows often sets PLATFORM) are ignored.
LINT      := 1
TYPECHECK := 1
TEST      := 0
I18N      := 1
PLATFORM  := android
PROFILE   := preview
-include local.mk

# What this repo actually has (1 = present). Set by the generator — do not edit by hand.
HAS_TYPECHECK := 0
HAS_TEST      := 1
HAS_VALIDATE  := 0
HAS_I18N      := 0

on = $(and $(filter 1,$(1)),$(filter 1,$(2)))
PRE := $(if $(filter 1,$(LINT)),lint) \
       $(if $(call on,$(TYPECHECK),$(HAS_TYPECHECK)),typecheck) \
       $(if $(call on,$(TEST),$(HAS_TEST)),test) \
       $(if $(call on,$(TEST),$(HAS_VALIDATE)),validate) \
       $(if $(call on,$(TEST),$(HAS_I18N)),i18n-report)

.DEFAULT_GOAL := help
.PHONY: help install lint lint-fix typecheck test validate i18n i18n-report check export \
        build build-lint build-test eas-build eas-build-local submit release doctor hooks clean

help:
	@echo "make install | lint | lint-fix | typecheck | test | i18n | check"
	@echo "make build | build-lint | build-test        (local, free)"
	@echo "make eas-build PROFILE=preview|production PLATFORM=android|ios|all   (EAS cloud quota)"
	@echo "make eas-build-local | submit | release | doctor | hooks | clean"
	@echo "toggles: LINT=$(LINT) TYPECHECK=$(TYPECHECK) TEST=$(TEST) I18N=$(I18N) PROFILE=$(PROFILE) PLATFORM=$(PLATFORM)"

install:
	npm ci

lint:
	npm run lint

lint-fix:
	npm run lint -- --fix

typecheck:
ifeq ($(HAS_TYPECHECK),1)
	npm run typecheck
else
	@echo "typecheck: not a TypeScript project, skipped"
endif

test:
ifeq ($(HAS_TEST),1)
	npm test
else
	@echo "test: no unit tests in this repo, skipped"
endif

validate:
ifeq ($(HAS_VALIDATE),1)
	npm run validate
endif

# Strict: fails when any language is missing a key.
i18n:
ifeq ($(HAS_I18N),1)
	npm run i18n:check
else
	@echo "i18n: no translations in this repo"
endif

# Used inside build-test: prints gaps but never blocks the build (set I18N=0 to skip).
i18n-report:
ifeq ($(I18N),1)
	-npm run i18n:check
endif

check:
	$(MAKE) lint typecheck test validate i18n TEST=1

# Local "build" = full JS bundle for the target platform. Catches bad imports, missing assets
# and config errors without spending EAS or GitHub minutes. Output: .build/ (git-ignored).
export:
	npx expo export --platform $(if $(filter all,$(PLATFORM)),all,$(PLATFORM)) --output-dir .build --clear

build: $(PRE)
	$(MAKE) export

build-lint:
	$(MAKE) build LINT=1

build-test:
	$(MAKE) build LINT=1 TEST=1

eas-build: $(PRE)
	npx eas-cli@latest build --platform $(PLATFORM) --profile $(PROFILE)

# Builds on this machine instead of EAS servers (free, but needs Android SDK/JDK; Linux/macOS/WSL only).
eas-build-local: $(PRE)
	npx eas-cli@latest build --local --platform $(PLATFORM) --profile $(PROFILE)

submit:
	npx eas-cli@latest submit --platform $(PLATFORM) --profile production --latest

release:
	$(MAKE) build-test
	npx eas-cli@latest build --platform $(PLATFORM) --profile production --auto-submit-with-profile production

doctor:
	npx expo-doctor@latest

# Run lint automatically before every git push (skip once with: git push --no-verify).
hooks:
	git config core.hooksPath .githooks
	@echo "pre-push lint hook enabled"

clean:
	node -e "require('fs').rmSync('.build',{recursive:true,force:true})"
